### ISSUE TITLE
Crashes when I press the refresh curse data for selected mod button

### ISSUE THREAD

**Issue by natanfudge** [calloatti/modrobot#10]
![image](https://user-images.githubusercontent.com/25990014/64910497-bc9eea00-d71f-11e9-8762-8c4b9da8d07f.png)

This is the log
```
DATETIME: 2019-09-14T18:42:32
ERROR   : 5
MESSAGE : Record is out of range.
LINENO  : 10
PROGRAM : MR_MODS.TBREFRESH.CLICK
LOG FILE: C:\Users\natan\AppData\Local\Programs\modrobot\modrobot.log
----------------------------------------------------------------------------
```

**Comment by calloatti** [comment]
In your screenshot there are no mods listed, so its logical that the curse button crashes, since there are none to zero safeguards against incorrect usage.

You have to click SCAN first to scan the mods folder and fill the grid with your mods, trying to find updated versions of a list of mods when your list contains no mods is not contemplated.

**Comment by calloatti** [comment]
I just noticed that you clicked this button:

![image](https://user-images.githubusercontent.com/12817862/64952358-8748e800-d856-11e9-9033-eed00b77eafa.png)

As the tooltip says. that button downloads curse info for the selected mod, since you have no mods, of course there is no selected mod.

You also did not set the instance min and max Minecraft version. Copy paste from the wiki:

Opens the mods window for the last selected instance.

MINVER and MAXVER

Sets Min and Max Minecraft versions if the instance. For example: 1.14 and 1.14.2. This is used when searching for mod updates.

SCAN

Scans the instance mods folder. Click "GET" to download all the mod data available.

DEPS

Opens the dependencies window for the instance.

REFRESH ALL

Downloads Curse data for all the mods

REFRESH

Downloads Curse data for the currently selected mod.

VERSIONS

Opens versions list, where you can pick the file to download when updating the mod. This enables you to upgrade/downgrade a mod version.

UPDATE ALL

Updates all the mod jars

UPDATE

Updates the currently selected mod jar

E\D

Enables/disables the mod by appending ".disabled" to the file name, like MultiMC

INSTANCES

Opens Intances menu to select another instance.

Double-Click on a mod to toggle "INCLUDE IN UPDATE ALL" (last column, UPD)

https://github.com/calloatti/modrobot/wiki

**Comment by natanfudge** [comment]
Yes, I understand that was bad user input, but bad user input shouldn’t crash the program lol.

**Comment by calloatti** [comment]
Agree, but I am lazy and just sharing something I did for my own use.
